# Generated by ocaml-tools

.PHONY: all clean

DESTDIR                   := _build
OCAMLOPT                  := ocamlopt
OCAMLC                    := ocamlc
OCAMLMKTOP                := ocamlmktop
CAMLP4O                   := camlp4o
COMPFLAGS_project         := $(shell ocamlfind query cmdliner -r -predicates byte -format "-I %d")
COMPFLAGS_ocamlfind       := 
COMPFLAGS_makefile        := 
LINK_opam-configure       := $(shell ocamlfind query cmdliner unix -r -predicates native -format "-I %d %a")
COMPFLAGS_opam_configure  := -I _build/tools $(shell ocamlfind query unix -r -predicates byte -format "-I %d")
LINKTOP_configure.top     := $(shell ocamlfind query cmdliner -r -predicates byte -format "-I %d %a")

all: tools opam-configure configure.top
	@

clean: 
	rm -f *~ **/*~
	rm -rf $(DESTDIR)

tools: $(DESTDIR)/tools.cma $(DESTDIR)/tools.cmxa
	@

$(DESTDIR)/tools.cma: $(DESTDIR)/tools/project.cmo $(DESTDIR)/tools/ocamlfind.cmo $(DESTDIR)/tools/makefile.cmo $(DESTDIR)/tools/project.cmi $(DESTDIR)/tools/ocamlfind.cmi $(DESTDIR)/tools/makefile.cmi
	$(OCAMLC) -a $(DESTDIR)/tools/project.cmo $(DESTDIR)/tools/ocamlfind.cmo $(DESTDIR)/tools/makefile.cmo -o $@

$(DESTDIR)/tools.cmxa: $(DESTDIR)/tools/project.cmx $(DESTDIR)/tools/ocamlfind.cmx $(DESTDIR)/tools/makefile.cmx $(DESTDIR)/tools/project.cmi $(DESTDIR)/tools/ocamlfind.cmi $(DESTDIR)/tools/makefile.cmi
	$(OCAMLOPT) -a $(DESTDIR)/tools/project.cmx $(DESTDIR)/tools/ocamlfind.cmx $(DESTDIR)/tools/makefile.cmx -o $@

$(DESTDIR)/tools/project.ml: lib/project.ml
	mkdir -p $(DESTDIR)/tools
	ln -sf $(shell pwd)/lib/project.ml $(DESTDIR)/tools/project.ml

$(DESTDIR)/tools/project.mli: lib/project.mli
	mkdir -p $(DESTDIR)/tools
	ln -sf $(shell pwd)/lib/project.mli $(DESTDIR)/tools/project.mli

$(DESTDIR)/tools/project.cmi: $(DESTDIR)/tools/project.mli
	$(OCAMLC) -c -I $(DESTDIR)/tools $(COMPFLAGS_project) $<

$(DESTDIR)/tools/project.cmo: $(DESTDIR)/tools/project.ml $(DESTDIR)/tools/project.cmi
	$(OCAMLC) -c -I $(DESTDIR)/tools $(COMPFLAGS_project) $<

$(DESTDIR)/tools/project.cmx: $(DESTDIR)/tools/project.ml $(DESTDIR)/tools/project.cmi
	$(OCAMLOPT) -c -I $(DESTDIR)/tools $(COMPFLAGS_project) $<

$(DESTDIR)/tools/ocamlfind.ml: lib/ocamlfind.ml
	mkdir -p $(DESTDIR)/tools
	ln -sf $(shell pwd)/lib/ocamlfind.ml $(DESTDIR)/tools/ocamlfind.ml

$(DESTDIR)/tools/ocamlfind.mli: lib/ocamlfind.mli
	mkdir -p $(DESTDIR)/tools
	ln -sf $(shell pwd)/lib/ocamlfind.mli $(DESTDIR)/tools/ocamlfind.mli

$(DESTDIR)/tools/ocamlfind.cmi: $(DESTDIR)/tools/ocamlfind.mli $(DESTDIR)/tools/project.cmi
	$(OCAMLC) -c -I $(DESTDIR)/tools $(COMPFLAGS_ocamlfind) $<

$(DESTDIR)/tools/ocamlfind.cmo: $(DESTDIR)/tools/ocamlfind.ml $(DESTDIR)/tools/ocamlfind.cmi $(DESTDIR)/tools/project.cmi
	$(OCAMLC) -c -I $(DESTDIR)/tools $(COMPFLAGS_ocamlfind) $<

$(DESTDIR)/tools/ocamlfind.cmx: $(DESTDIR)/tools/ocamlfind.ml $(DESTDIR)/tools/ocamlfind.cmi $(DESTDIR)/tools/project.cmi
	$(OCAMLOPT) -c -I $(DESTDIR)/tools $(COMPFLAGS_ocamlfind) $<

$(DESTDIR)/tools/makefile.ml: lib/makefile.ml
	mkdir -p $(DESTDIR)/tools
	ln -sf $(shell pwd)/lib/makefile.ml $(DESTDIR)/tools/makefile.ml

$(DESTDIR)/tools/makefile.mli: lib/makefile.mli
	mkdir -p $(DESTDIR)/tools
	ln -sf $(shell pwd)/lib/makefile.mli $(DESTDIR)/tools/makefile.mli

$(DESTDIR)/tools/makefile.cmi: $(DESTDIR)/tools/makefile.mli $(DESTDIR)/tools/project.cmi $(DESTDIR)/tools/ocamlfind.cmi
	$(OCAMLC) -c -I $(DESTDIR)/tools $(COMPFLAGS_makefile) $<

$(DESTDIR)/tools/makefile.cmo: $(DESTDIR)/tools/makefile.ml $(DESTDIR)/tools/makefile.cmi $(DESTDIR)/tools/project.cmi $(DESTDIR)/tools/ocamlfind.cmi
	$(OCAMLC) -c -I $(DESTDIR)/tools $(COMPFLAGS_makefile) $<

$(DESTDIR)/tools/makefile.cmx: $(DESTDIR)/tools/makefile.ml $(DESTDIR)/tools/makefile.cmi $(DESTDIR)/tools/project.cmi $(DESTDIR)/tools/ocamlfind.cmi
	$(OCAMLOPT) -c -I $(DESTDIR)/tools $(COMPFLAGS_makefile) $<

opam-configure: $(DESTDIR)/tools.cmxa $(DESTDIR)/opam-configure/opam_configure.cmx
	$(OCAMLOPT) $(LINK_opam-configure) $^ -o $@

$(DESTDIR)/opam-configure/opam_configure.ml: lib/opam_configure.ml
	mkdir -p $(DESTDIR)/opam-configure
	ln -sf $(shell pwd)/lib/opam_configure.ml $(DESTDIR)/opam-configure/opam_configure.ml

$(DESTDIR)/opam-configure/opam_configure.cmo $(DESTDIR)/opam-configure/opam_configure.cmi: $(DESTDIR)/opam-configure/opam_configure.ml $(DESTDIR)/tools/project.cmx $(DESTDIR)/tools/ocamlfind.cmx $(DESTDIR)/tools/makefile.cmx $(DESTDIR)/tools/project.cmi $(DESTDIR)/tools/ocamlfind.cmi $(DESTDIR)/tools/makefile.cmi
	$(OCAMLC) -c -I $(DESTDIR)/opam-configure $(COMPFLAGS_opam_configure) $<

$(DESTDIR)/opam-configure/opam_configure.cmx: $(DESTDIR)/opam-configure/opam_configure.ml $(DESTDIR)/opam-configure/opam_configure.cmi $(DESTDIR)/tools/project.cmx $(DESTDIR)/tools/ocamlfind.cmx $(DESTDIR)/tools/makefile.cmx $(DESTDIR)/tools/project.cmi $(DESTDIR)/tools/ocamlfind.cmi $(DESTDIR)/tools/makefile.cmi
	$(OCAMLOPT) -c -I $(DESTDIR)/opam-configure $(COMPFLAGS_opam_configure) $<

configure.top: $(DESTDIR)/tools.cma
	$(OCAMLMKTOP) LINKTOP_configure.top $^ -o $@

