# Generated by ocaml-tools

.PHONY: all clean

DESTDIR                   := _build
OCAMLOPT                  := ocamlopt
OCAMLC                    := ocamlc
OCAMLMKTOP                := ocamlmktop
CAMLP4O                   := camlp4o
COMPFLAGS_git             := 
COMPFLAGS_project         := $(shell ocamlfind query cmdliner -r -predicates byte -format "-I %d")
COMPFLAGS_ocamlfind       := 
COMPFLAGS_opam            := $(shell ocamlfind query opam -r -predicates byte -format "-I %d")
COMPFLAGS_makefile        := 
COMPFLAGS_tools           := 
LINK_opam-configure       := $(shell ocamlfind query opam cmdliner unix -r -predicates native -format "-I %d %a")
COMPFLAGS_opam_configure  := -I _build/tools $(shell ocamlfind query unix -r -predicates byte -format "-I %d")
LINKTOP_configure.top     := $(shell ocamlfind query opam cmdliner -r -predicates byte -format "-I %d %a")

all: tools opam-configure configure.top
	@

clean: 
	rm -f *~ **/*~
	rm -rf $(DESTDIR)

tools: $(DESTDIR)/tools/tools.cma $(DESTDIR)/tools/tools.cmxa $(DESTDIR)/tools/tools.cmxs
	@

$(DESTDIR)/tools/tools.cma: $(DESTDIR)/tools/git.cmo $(DESTDIR)/tools/project.cmo $(DESTDIR)/tools/ocamlfind.cmo $(DESTDIR)/tools/opam.cmo $(DESTDIR)/tools/makefile.cmo $(DESTDIR)/tools/tools.cmo $(DESTDIR)/tools/git.cmi $(DESTDIR)/tools/project.cmi $(DESTDIR)/tools/ocamlfind.cmi $(DESTDIR)/tools/opam.cmi $(DESTDIR)/tools/makefile.cmi $(DESTDIR)/tools/tools.cmi
	$(OCAMLC) -a $(DESTDIR)/tools/git.cmo $(DESTDIR)/tools/project.cmo $(DESTDIR)/tools/ocamlfind.cmo $(DESTDIR)/tools/opam.cmo $(DESTDIR)/tools/makefile.cmo $(DESTDIR)/tools/tools.cmo -o $@

$(DESTDIR)/tools/tools.cmxa: $(DESTDIR)/tools/git.cmx $(DESTDIR)/tools/project.cmx $(DESTDIR)/tools/ocamlfind.cmx $(DESTDIR)/tools/opam.cmx $(DESTDIR)/tools/makefile.cmx $(DESTDIR)/tools/tools.cmx $(DESTDIR)/tools/git.cmi $(DESTDIR)/tools/project.cmi $(DESTDIR)/tools/ocamlfind.cmi $(DESTDIR)/tools/opam.cmi $(DESTDIR)/tools/makefile.cmi $(DESTDIR)/tools/tools.cmi
	$(OCAMLOPT) -a $(DESTDIR)/tools/git.cmx $(DESTDIR)/tools/project.cmx $(DESTDIR)/tools/ocamlfind.cmx $(DESTDIR)/tools/opam.cmx $(DESTDIR)/tools/makefile.cmx $(DESTDIR)/tools/tools.cmx -o $@

$(DESTDIR)/tools/tools.cmxs: $(DESTDIR)/tools/git.cmx $(DESTDIR)/tools/project.cmx $(DESTDIR)/tools/ocamlfind.cmx $(DESTDIR)/tools/opam.cmx $(DESTDIR)/tools/makefile.cmx $(DESTDIR)/tools/tools.cmx $(DESTDIR)/tools/git.cmi $(DESTDIR)/tools/project.cmi $(DESTDIR)/tools/ocamlfind.cmi $(DESTDIR)/tools/opam.cmi $(DESTDIR)/tools/makefile.cmi $(DESTDIR)/tools/tools.cmi
	$(OCAMLOPT) -shared $(DESTDIR)/tools/git.cmx $(DESTDIR)/tools/project.cmx $(DESTDIR)/tools/ocamlfind.cmx $(DESTDIR)/tools/opam.cmx $(DESTDIR)/tools/makefile.cmx $(DESTDIR)/tools/tools.cmx -o $@

$(DESTDIR)/tools/git.ml: lib/git.ml
	mkdir -p $(DESTDIR)/tools
	ln -sf $(shell pwd)/lib/git.ml $(DESTDIR)/tools/git.ml

$(DESTDIR)/tools/git.mli: lib/git.mli
	mkdir -p $(DESTDIR)/tools
	ln -sf $(shell pwd)/lib/git.mli $(DESTDIR)/tools/git.mli

$(DESTDIR)/tools/git.cmi: $(DESTDIR)/tools/git.mli
	$(OCAMLC) -c -I $(DESTDIR)/tools $(COMPFLAGS_git) $<

$(DESTDIR)/tools/git.cmo: $(DESTDIR)/tools/git.ml $(DESTDIR)/tools/git.cmi
	$(OCAMLC) -c -I $(DESTDIR)/tools $(COMPFLAGS_git) $<

$(DESTDIR)/tools/git.cmx: $(DESTDIR)/tools/git.ml $(DESTDIR)/tools/git.cmi
	$(OCAMLOPT) -c -I $(DESTDIR)/tools $(COMPFLAGS_git) $<

$(DESTDIR)/tools/project.ml: lib/project.ml
	mkdir -p $(DESTDIR)/tools
	ln -sf $(shell pwd)/lib/project.ml $(DESTDIR)/tools/project.ml

$(DESTDIR)/tools/project.mli: lib/project.mli
	mkdir -p $(DESTDIR)/tools
	ln -sf $(shell pwd)/lib/project.mli $(DESTDIR)/tools/project.mli

$(DESTDIR)/tools/project.cmi: $(DESTDIR)/tools/project.mli $(DESTDIR)/tools/git.cmi
	$(OCAMLC) -c -I $(DESTDIR)/tools $(COMPFLAGS_project) $<

$(DESTDIR)/tools/project.cmo: $(DESTDIR)/tools/project.ml $(DESTDIR)/tools/project.cmi $(DESTDIR)/tools/git.cmi
	$(OCAMLC) -c -I $(DESTDIR)/tools $(COMPFLAGS_project) $<

$(DESTDIR)/tools/project.cmx: $(DESTDIR)/tools/project.ml $(DESTDIR)/tools/project.cmi $(DESTDIR)/tools/git.cmx
	$(OCAMLOPT) -c -I $(DESTDIR)/tools $(COMPFLAGS_project) $<

$(DESTDIR)/tools/ocamlfind.ml: lib/ocamlfind.ml
	mkdir -p $(DESTDIR)/tools
	ln -sf $(shell pwd)/lib/ocamlfind.ml $(DESTDIR)/tools/ocamlfind.ml

$(DESTDIR)/tools/ocamlfind.mli: lib/ocamlfind.mli
	mkdir -p $(DESTDIR)/tools
	ln -sf $(shell pwd)/lib/ocamlfind.mli $(DESTDIR)/tools/ocamlfind.mli

$(DESTDIR)/tools/ocamlfind.cmi: $(DESTDIR)/tools/ocamlfind.mli $(DESTDIR)/tools/project.cmi
	$(OCAMLC) -c -I $(DESTDIR)/tools $(COMPFLAGS_ocamlfind) $<

$(DESTDIR)/tools/ocamlfind.cmo: $(DESTDIR)/tools/ocamlfind.ml $(DESTDIR)/tools/ocamlfind.cmi $(DESTDIR)/tools/project.cmi
	$(OCAMLC) -c -I $(DESTDIR)/tools $(COMPFLAGS_ocamlfind) $<

$(DESTDIR)/tools/ocamlfind.cmx: $(DESTDIR)/tools/ocamlfind.ml $(DESTDIR)/tools/ocamlfind.cmi $(DESTDIR)/tools/project.cmx
	$(OCAMLOPT) -c -I $(DESTDIR)/tools $(COMPFLAGS_ocamlfind) $<

$(DESTDIR)/tools/opam.ml: lib/opam.ml
	mkdir -p $(DESTDIR)/tools
	ln -sf $(shell pwd)/lib/opam.ml $(DESTDIR)/tools/opam.ml

$(DESTDIR)/tools/opam.mli: lib/opam.mli
	mkdir -p $(DESTDIR)/tools
	ln -sf $(shell pwd)/lib/opam.mli $(DESTDIR)/tools/opam.mli

$(DESTDIR)/tools/opam.cmi: $(DESTDIR)/tools/opam.mli $(DESTDIR)/tools/project.cmi
	$(OCAMLC) -c -I $(DESTDIR)/tools $(COMPFLAGS_opam) $<

$(DESTDIR)/tools/opam.cmo: $(DESTDIR)/tools/opam.ml $(DESTDIR)/tools/opam.cmi $(DESTDIR)/tools/project.cmi
	$(OCAMLC) -c -I $(DESTDIR)/tools $(COMPFLAGS_opam) $<

$(DESTDIR)/tools/opam.cmx: $(DESTDIR)/tools/opam.ml $(DESTDIR)/tools/opam.cmi $(DESTDIR)/tools/project.cmx
	$(OCAMLOPT) -c -I $(DESTDIR)/tools $(COMPFLAGS_opam) $<

$(DESTDIR)/tools/makefile.ml: lib/makefile.ml
	mkdir -p $(DESTDIR)/tools
	ln -sf $(shell pwd)/lib/makefile.ml $(DESTDIR)/tools/makefile.ml

$(DESTDIR)/tools/makefile.mli: lib/makefile.mli
	mkdir -p $(DESTDIR)/tools
	ln -sf $(shell pwd)/lib/makefile.mli $(DESTDIR)/tools/makefile.mli

$(DESTDIR)/tools/makefile.cmi: $(DESTDIR)/tools/makefile.mli $(DESTDIR)/tools/project.cmi $(DESTDIR)/tools/ocamlfind.cmi
	$(OCAMLC) -c -I $(DESTDIR)/tools $(COMPFLAGS_makefile) $<

$(DESTDIR)/tools/makefile.cmo: $(DESTDIR)/tools/makefile.ml $(DESTDIR)/tools/makefile.cmi $(DESTDIR)/tools/project.cmi $(DESTDIR)/tools/ocamlfind.cmi
	$(OCAMLC) -c -I $(DESTDIR)/tools $(COMPFLAGS_makefile) $<

$(DESTDIR)/tools/makefile.cmx: $(DESTDIR)/tools/makefile.ml $(DESTDIR)/tools/makefile.cmi $(DESTDIR)/tools/project.cmx $(DESTDIR)/tools/ocamlfind.cmx
	$(OCAMLOPT) -c -I $(DESTDIR)/tools $(COMPFLAGS_makefile) $<

$(DESTDIR)/tools/tools.ml: lib/tools.ml
	mkdir -p $(DESTDIR)/tools
	ln -sf $(shell pwd)/lib/tools.ml $(DESTDIR)/tools/tools.ml

$(DESTDIR)/tools/tools.mli: lib/tools.mli
	mkdir -p $(DESTDIR)/tools
	ln -sf $(shell pwd)/lib/tools.mli $(DESTDIR)/tools/tools.mli

$(DESTDIR)/tools/tools.cmi: $(DESTDIR)/tools/tools.mli $(DESTDIR)/tools/makefile.cmi $(DESTDIR)/tools/ocamlfind.cmi $(DESTDIR)/tools/opam.cmi
	$(OCAMLC) -c -I $(DESTDIR)/tools $(COMPFLAGS_tools) $<

$(DESTDIR)/tools/tools.cmo: $(DESTDIR)/tools/tools.ml $(DESTDIR)/tools/tools.cmi $(DESTDIR)/tools/makefile.cmi $(DESTDIR)/tools/ocamlfind.cmi $(DESTDIR)/tools/opam.cmi
	$(OCAMLC) -c -I $(DESTDIR)/tools $(COMPFLAGS_tools) $<

$(DESTDIR)/tools/tools.cmx: $(DESTDIR)/tools/tools.ml $(DESTDIR)/tools/tools.cmi $(DESTDIR)/tools/makefile.cmx $(DESTDIR)/tools/ocamlfind.cmx $(DESTDIR)/tools/opam.cmx
	$(OCAMLOPT) -c -I $(DESTDIR)/tools $(COMPFLAGS_tools) $<

opam-configure: $(DESTDIR)/opam-configure/opam-configure
	@

$(DESTDIR)/opam-configure/opam-configure: $(DESTDIR)/tools/tools.cmxa $(DESTDIR)/opam-configure/opam_configure.cmx
	$(OCAMLOPT) $(LINK_opam-configure) $^ -o $@

$(DESTDIR)/opam-configure/opam_configure.ml: lib/opam_configure.ml
	mkdir -p $(DESTDIR)/opam-configure
	ln -sf $(shell pwd)/lib/opam_configure.ml $(DESTDIR)/opam-configure/opam_configure.ml

$(DESTDIR)/opam-configure/opam_configure.cmo $(DESTDIR)/opam-configure/opam_configure.cmi: $(DESTDIR)/opam-configure/opam_configure.ml $(DESTDIR)/tools/git.cmi $(DESTDIR)/tools/project.cmi $(DESTDIR)/tools/ocamlfind.cmi $(DESTDIR)/tools/opam.cmi $(DESTDIR)/tools/makefile.cmi $(DESTDIR)/tools/tools.cmi $(DESTDIR)/tools/git.cmi $(DESTDIR)/tools/project.cmi $(DESTDIR)/tools/ocamlfind.cmi $(DESTDIR)/tools/opam.cmi $(DESTDIR)/tools/makefile.cmi $(DESTDIR)/tools/tools.cmi
	$(OCAMLC) -c -I $(DESTDIR)/opam-configure $(COMPFLAGS_opam_configure) $<

$(DESTDIR)/opam-configure/opam_configure.cmx: $(DESTDIR)/opam-configure/opam_configure.ml $(DESTDIR)/opam-configure/opam_configure.cmi $(DESTDIR)/tools/git.cmx $(DESTDIR)/tools/project.cmx $(DESTDIR)/tools/ocamlfind.cmx $(DESTDIR)/tools/opam.cmx $(DESTDIR)/tools/makefile.cmx $(DESTDIR)/tools/tools.cmx $(DESTDIR)/tools/git.cmx $(DESTDIR)/tools/project.cmx $(DESTDIR)/tools/ocamlfind.cmx $(DESTDIR)/tools/opam.cmx $(DESTDIR)/tools/makefile.cmx $(DESTDIR)/tools/tools.cmx
	$(OCAMLOPT) -c -I $(DESTDIR)/opam-configure $(COMPFLAGS_opam_configure) $<

configure.top: $(DESTDIR)/configure.top/configure.top
	@

$(DESTDIR)/configure.top/configure.top: $(DESTDIR)/tools/tools.cma
	mkdir -p $(DESTDIR)/configure.top
	$(OCAMLMKTOP) $(LINKTOP_configure.top) $^ -o $@

